hwdec=auto-safe

# Allow going to the next / previous media file in the current directory even
# if you open an individual file (such as opening a file with a file explorer).
#
# When using "same", images will only cycle images and the same goes with videos.
#
# Also don't recurse into directories, "ignore" locks it to the current directory.
autocreate-playlist=same
directory-mode=ignore

[pause]
profile-cond=pause
profile-restore=copy
script-opt=osc-visibility=always

[builtin-pseudo-gui]
keep-open=yes
screenshot-directory=~/Pictures
